### ISSUE TITLE
Introspect sources and dry run requests on pfs:deploy

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-feeds#46]

**Comment by Tommytrg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Witnet-Foundation-5c13a9364d778414b5ba555c/issues/witnet/witnet-feeds/46?planning-poker) with Zenhub @aesedepece @aeweda @gabaldon @guidiaz

**Comment by guidiaz** [comment]
![image](https://github.com/user-attachments/assets/1fc4105e-d702-4e02-b493-6099fea5a949)

**Comment by Tommytrg** [comment]
Merged in https://github.com/witnet/witnet-feeds/tree/2.1.x
