### ISSUE TITLE
Optionally estimate current deviation percentage on pfs:status

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-feeds#47]

**Comment by Tommytrg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Witnet-Foundation-5c13a9364d778414b5ba555c/issues/witnet/witnet-feeds/47?planning-poker) with Zenhub @aesedepece @aeweda @gabaldon @guidiaz

**Comment by guidiaz** [comment]
![image](https://github.com/user-attachments/assets/4a4de2fd-c0c1-4a1e-a686-12c68b3283bb)

**Comment by Tommytrg** [comment]
Merged in https://github.com/witnet/witnet-feeds/tree/2.1.x
